# Generated by Django 5.0 on 2025-04-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('marketplace1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='collection.card'),
        ),
    ]
