# Generated by Django 5.2 on 2025-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.URLField(default='https://allroundclub.com/blog/wp-content/uploads/2021/10/how-to-draw-pikachu.png'),
            preserve_default=False,
        ),
    ]
