# Generated by Django 5.0 on 2025-04-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0002_remove_card_owner_id_alter_listing_card'),
        ('orders', '0002_alter_order_card'),
        ('trade', '0002_alter_listingfortrading_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
