# Generated by Django 5.0 on 2025-04-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfortrading',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_listings', to='collection.card'),
        ),
        migrations.AlterField(
            model_name='offertrade',
            name='card_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='collection.card'),
        ),
    ]
