# Generated by Django 5.0 on 2025-04-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_listingfortrading_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingfortrading',
            old_name='card',
            new_name='listed_card',
        ),
        migrations.RenameField(
            model_name='offertrade',
            old_name='card_offered',
            new_name='offered_card',
        ),
    ]
