# Generated by Django 5.0 on 2025-04-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card',
            new_name='purchased_card',
        ),
    ]
